In [56]:
# import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import psycopg2
import seaborn as sns
import random
from sqlalchemy import create_engine, inspect
from cleaning import clean_data
from cleaning import fix_data_type
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import os

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [57]:
# connect to database
db_params = "postgresql://amiin123:Ismail6566!@localhost:5433/heartdisease"


# Load the CSV file into a DataFrame
df = pd.read_csv('heart_disease.csv')

df.rename(columns={'ekgday(day': 'ekgday'}, inplace=True)

df = clean_data(df)


# Database connection string
conn_string = "postgresql://amiin123:Ismail6566!@localhost:5433/heartdisease_db"

# Create an engine and connect to the database
engine = create_engine(conn_string)
conn = engine.connect()

# Insert data into the heartdisease_data table
df.to_sql('heartdisease_data', conn, if_exists='append', index=False)

# Close the connection
conn.close()

/Users/amiin/Desktop/DE300/Homework1/cleaning.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(value=median_value, inplace=True)
/Users/amiin/Desktop/DE300/Homework1/cleaning.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(value=median_value, inplace=True)
/Users/amiin/Desktop/DE300/Homework1/cleaning.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(value=mode_value, inplace=True)
/Users/amiin/Desktop/DE300/Homework1/cleaning.py:34: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [58]:
df.head()

    age  sex  painloc  painexer  relrest  pncaden   cp  trestbps  htn   chol  smoke  cigs  years  fbs  dm  famhist  restecg  ekgmo  ekgday  ekgyr  dig  prop  nitr  pro  diuretic  proto  thaldur  thaltime   met  thalach  thalrest  tpeakbps  tpeakbpd  dummy  trestbpd  exang  xhypo  oldpeak  slope  rldv5  rldv5e   ca  restckm  exerckm  restef  restwm  exeref  exerwm  thal  thalsev  thalpul  earlobe  cmo  cday   cyr  target
0  63.0  1.0      1.0       1.0      NaN      NaN  1.0     145.0  1.0  233.0    NaN  50.0   20.0  1.0 NaN      1.0      2.0    2.0     3.0   81.0  0.0   0.0   0.0  0.0       0.0    1.0     10.5       6.0  13.0    150.0      60.0     190.0      90.0  145.0      85.0    0.0    0.0      2.3    3.0    NaN   172.0  0.0      NaN      NaN     NaN     NaN     NaN     NaN   6.0      NaN      NaN      NaN  2.0  16.0  81.0     0.0
1  67.0  1.0      1.0       1.0      NaN      NaN  4.0     160.0  1.0  286.0    NaN  40.0   40.0  0.0 NaN      1.0      2.0    3.0     5.0   81.0  0.0   1.0   0.0  0.0       0.0    1.0      9.5       6.0  13.0    108.0      64.0     160.0      90.0  160.0      90.0    1.0    0.0      1.5    2.0    NaN   185.0  3.0      NaN      NaN     NaN     NaN     NaN     NaN   3.0      NaN      NaN      NaN  2.0   5.0  81.0     1.0
2  67.0  1.0      1.0       1.0      NaN      NaN  4.0     120.0  1.0  229.0    NaN  20.0   35.0  0.0 NaN      1.0      2.0    2.0    19.0   81.0  0.0   1.0   0.0  0.0       0.0    1.0      8.5       6.0  10.0    129.0      78.0     140.0      80.0  120.0      80.0    1.0    0.0      2.6    2.0    NaN   150.0  2.0      NaN      NaN     NaN     NaN     NaN     NaN   7.0      NaN      NaN      NaN  2.0  20.0  81.0     1.0
3  37.0  1.0      1.0       1.0      NaN      NaN  3.0     130.0  0.0  250.0    NaN   0.0    0.0  0.0 NaN      1.0      0.0    2.0    13.0   81.0  0.0   1.0   0.0  0.0       0.0    1.0     13.0      13.0  17.0    187.0      84.0     195.0      68.0  130.0      78.0    0.0    0.0      3.5    3.0    NaN   167.0  0.0      NaN      NaN     NaN     NaN     NaN     NaN   3.0      NaN      NaN      NaN  2.0   4.0  81.0     0.0
4  41.0  0.0      1.0       1.0      NaN      NaN  2.0     130.0  1.0  204.0    NaN   0.0    0.0  0.0 NaN      1.0      2.0    2.0     7.0   81.0  0.0   0.0   0.0  0.0       0.0    1.0      7.0       NaN   9.0    172.0      71.0     160.0      74.0  130.0      86.0    0.0    0.0      1.4    1.0    NaN    40.0  0.0      NaN      NaN     NaN     NaN     NaN     NaN   3.0      NaN      NaN      NaN  2.0  18.0  81.0     0.0

In [59]:
## fetch from data

# Database connection string
conn_string = "postgresql://amiin123:Ismail6566!@localhost:5433/heartdisease_db"

# Create an engine and connect to the database
engine = create_engine(conn_string)
conn = engine.connect()

# Fetch data from the heartdisease_data table
query = "SELECT * FROM heartdisease_data"
df = pd.read_sql(query, conn)

# Close the connection
conn.close()

# Display the DataFrame
df.head()

   age  sex  painloc  painexer  relrest pncaden   cp  trestbps  htn   chol  smoke  cigs  years  fbs  dm  famhist  restecg  ekgmo  ekgday  ekgyr  dig  prop  nitr  pro  diuretic  proto  thaldur  thaltime   met  thalach  thalrest  tpeakbps  tpeakbpd  dummy  trestbpd  exang  xhypo  oldpeak  slope  rldv5  rldv5e   ca restckm  exerckm  restef  restwm  exeref  exerwm  thal  thalsev  thalpul  earlobe  cmo  cday   cyr  target
0   63  1.0      1.0       1.0      NaN    None  1.0     145.0  1.0  233.0    NaN  50.0   20.0  1.0 NaN      1.0      2.0    2.0     3.0   81.0  0.0   0.0   0.0  0.0       0.0    1.0     10.5       6.0  13.0    150.0      60.0     190.0      90.0  145.0      85.0    0.0    0.0      2.3    3.0    NaN   172.0  0.0    None      NaN     NaN     NaN     NaN     NaN   6.0      NaN      NaN      NaN  2.0  16.0  81.0     0.0
1   67  1.0      1.0       1.0      NaN    None  4.0     160.0  1.0  286.0    NaN  40.0   40.0  0.0 NaN      1.0      2.0    3.0     5.0   81.0  0.0   1.0   0.0  0.0       0.0    1.0      9.5       6.0  13.0    108.0      64.0     160.0      90.0  160.0      90.0    1.0    0.0      1.5    2.0    NaN   185.0  3.0    None      NaN     NaN     NaN     NaN     NaN   3.0      NaN      NaN      NaN  2.0   5.0  81.0     1.0
2   67  1.0      1.0       1.0      NaN    None  4.0     120.0  1.0  229.0    NaN  20.0   35.0  0.0 NaN      1.0      2.0    2.0    19.0   81.0  0.0   1.0   0.0  0.0       0.0    1.0      8.5       6.0  10.0    129.0      78.0     140.0      80.0  120.0      80.0    1.0    0.0      2.6    2.0    NaN   150.0  2.0    None      NaN     NaN     NaN     NaN     NaN   7.0      NaN      NaN      NaN  2.0  20.0  81.0     1.0
3   37  1.0      1.0       1.0      NaN    None  3.0     130.0  0.0  250.0    NaN   0.0    0.0  0.0 NaN      1.0      0.0    2.0    13.0   81.0  0.0   1.0   0.0  0.0       0.0    1.0     13.0      13.0  17.0    187.0      84.0     195.0      68.0  130.0      78.0    0.0    0.0      3.5    3.0    NaN   167.0  0.0    None      NaN     NaN     NaN     NaN     NaN   3.0      NaN      NaN      NaN  2.0   4.0  81.0     0.0
4   41  0.0      1.0       1.0      NaN    None  2.0     130.0  1.0  204.0    NaN   0.0    0.0  0.0 NaN      1.0      2.0    2.0     7.0   81.0  0.0   0.0   0.0  0.0       0.0    1.0      7.0       NaN   9.0    172.0      71.0     160.0      74.0  130.0      86.0    0.0    0.0      1.4    1.0    NaN    40.0  0.0    None      NaN     NaN     NaN     NaN     NaN   3.0      NaN      NaN      NaN  2.0  18.0  81.0     0.0

In [60]:
# analyzing Missing Values:
print("Checking missing values or NaN: ")
print(df.isnull().sum())

# data description
print("original data description...")
print(df.describe())

# Identifying categorical and numerical columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Removing the target variable from numerical_cols if it's there
numerical_cols = [col for col in numerical_cols if col != 'target']

Checking missing values or NaN:
age            0
sex           30
painloc        0
painexer       0
relrest      888
pncaden     2727
cp            30
trestbps       0
htn          132
chol           0
smoke       2037
cigs        1290
years       1326
fbs          300
dm          2442
famhist     1296
restecg       36
ekgmo        189
ekgday       192
ekgyr        189
dig          234
prop         228
nitr         225
pro          219
diuretic     276
proto        366
thaldur      198
thaltime    1389
met          345
thalach      195
thalrest     198
tpeakbps     219
tpeakbpd     219
dummy        207
trestbpd     207
exang        195
xhypo        204
oldpeak      216
slope        954
rldv5       1305
rldv5e       456
ca          1854
restckm     2727
exerckm     2724
restef      2643
restwm      2637
exeref      2721
exerwm      2712
thal        1461
thalsev     2337
thalpul     2595
earlobe     2724
cmo           63
cday          57
cyr           57
target        30
dtype: int64
original data description...
               age          sex      painloc     painexer      relrest           cp     trestbps          htn         chol       smoke         cigs        years          fbs          dm      famhist      restecg        ekgmo       ekgday        ekgyr          dig         prop         nitr          pro     diuretic        proto      thaldur     thaltime          met      thalach     thalrest     tpeakbps     tpeakbpd        dummy     trestbpd        exang        xhypo      oldpeak        slope        rldv5       rldv5e          ca  exerckm     restef     restwm    exeref     exerwm         thal     thalsev     thalpul  earlobe          cmo         cday          cyr       target
count  2727.000000  2697.000000  2727.000000  2727.000000  1839.000000  2697.000000  2727.000000  2595.000000  2727.000000  690.000000  1437.000000  1401.000000  2427.000000  285.000000  1431.000000  2691.000000  2538.000000  2535.000000  2538.000000  2493.000000  2499.000000  2502.000000  2508.000000  2451.000000  2361.000000  2529.000000  1338.000000  2382.000000  2532.000000  2529.000000  2508.000000  2508.000000  2520.000000  2520.000000  2532.000000  2523.000000  2511.000000  1773.000000  1422.000000  2271.000000  873.000000      3.0  84.000000  90.000000  6.000000  15.000000  1266.000000  390.000000  132.000000      3.0  2664.000000  2670.000000  2670.000000  2697.000000
mean     54.310231     0.790879     0.946095     0.723872     0.672104     3.253615   131.941694     0.476301   199.870187    0.517391    19.118998    18.796574     0.166873    0.957895     0.563941     0.603122     5.973995    15.493491    84.056738     0.034898     0.283313     0.266187     0.172249     0.112607    37.081321     8.655872     5.690359    16.483123   137.298578    75.487544   171.641148    87.293062   132.101190    83.523810     0.390995     0.026159     0.870490     1.766497    14.398734    54.914135    0.697595      0.0   0.531071   1.033333  0.550000   0.200000     5.018957    1.284615    0.295455      0.0     6.122748    15.988764    83.839326     0.550612
std      15.484064     0.406757     0.225872     0.447163     0.469574     0.928155    18.410754     0.499534   109.425814    0.500060    18.283527    16.347456     0.372939    0.201183     0.496068     0.803370     3.485104     8.758481     1.639557     0.183558     0.870616     0.442052     0.377672     0.316176    50.123307     3.745135     3.991684    30.759874    25.955698    14.722134    25.724221    14.728707    19.143523    10.248492     0.488070     0.159641     1.080118     0.620988     5.698927    60.282851    1.051520      0.0   0.144423   1.054152  0.054772   0.414039     1.947847    0.955848    0.457985      0.0     3.472810     8.857552     4.405881     0.497524
min       6.000000     0.000000     0.000000     0.000000     0.000000     1.000000     0.000000     0.000000     0.000000    0.000000     0.000000     0.000000     0.000000    0.000000     0.000000     0.000000     1.000000     1.000000    81.000000     0.000000     0.000000     0.000000     0.000000     0.000000     1.000000     1.000000     0.000000     2.000000    60.000000    37.000000    84.000000    11.000000     0.000000     0.000000     0.000000     0.000000    -2.600000     0.000000     2.000000     2.000000    0.000000      0.0   0.220000   0.000000  0.500000   0.000000     1.000000    0.000000    0.000000      0.0     1.000000     1.000000     1.000000     0.000000
25%      47.000000     1.000000     1.000000     0.000000     0.000000     3.000000   120.000000     0.000000   179.000000    0.000000     0.000000     0.000000     0.000000    1.000000     0.000000     0.000000     3.000000     8.000000    83.000000     0.000000     0.000000     0.000000     0.000000     0.000000     1.000000     6.000000     3.000000     5.000000   120.000000    65.000000   155.000000    80.000000   120.000000    80.000000     0.000000     0.000000     0.000000     1.000000    10.000000    12.000000    0.000000      0.0   0.407500   0.000000  0.500000   0.000000     3.000000    0.000000    0.000000      0.0     3.000000     8.000000    83.000000     0.000000
50%      54.000000     1.000000     1.000000     1.000000     1.000000     4.000000   130.000000     0.000000   224.000000    1.000000    20.000000    20.000000     0.000000    1.000000     1.000000     0.000000     6.000000    16.000000    84.000000     0.000000     0.000000     0.000000     0.000000     0.000000     5.000000     8.100000     6.000000     7.000000   140.000000    74.000000   170.000000    88.000000   130.000000    80.000000     0.000000     0.000000     0.500000     2.000000    14.000000    19.000000    0.000000      0.0   0.570000   1.000000  0.550000   0.000000     6.000000    1.000000    0.000000      0.0     6.000000    16.000000    84.000000     1.000000
75%      60.000000     1.000000     1.000000     1.000000     1.000000     4.000000   140.000000     1.000000   267.000000    1.000000    30.000000    30.000000     0.000000    1.000000     1.000000     1.000000     9.000000    23.000000    85.000000     0.000000     1.000000     1.000000     0.000000     0.000000    75.000000    10.500000     8.000000    10.000000   157.000000    84.000000   190.000000   100.000000   140.000000    90.000000     1.000000     0.000000     1.500000     2.000000    18.000000   102.000000    1.000000      0.0   0.625000   2.000000  0.600000   0.000000     7.000000    2.000000    1.000000      0.0     9.000000    24.000000    85.000000     1.000000
max     330.000000     1.000000     1.000000     1.000000     1.000000     4.000000   200.000000     1.000000   603.000000    1.000000    99.000000    60.000000     1.000000    1.000000     1.000000     2.000000    12.000000    31.000000    87.000000     1.000000    22.000000     1.000000     1.000000     1.000000   200.000000    24.000000    20.000000   200.000000   202.000000   139.000000   240.000000   134.000000   200.000000   120.000000     1.000000     1.000000     6.200000     3.000000    36.000000   270.000000    9.000000      0.0   0.800000   3.000000  0.600000   1.000000     7.000000    3.000000    1.000000      0.0    12.000000    31.000000    87.000000     1.000000

In [61]:

# Creating transformers
transformers = [
    ('num', StandardScaler(), numerical_cols),
    ('cat', OneHotEncoder(), categorical_cols)
]

# Combining transformers into a single preprocessor
preprocessor = ColumnTransformer(transformers)

# Applying transformations
print("After applied tranformations descriptions... ")
df_transformed = preprocessor.fit_transform(df)

# Optional: Convert transformed data back to a DataFrame
# This part assumes you want to see the transformed DataFrame
transformed_columns = preprocessor.transformers_[0][2] + \
    list(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols))
df_transformed = pd.DataFrame(df_transformed, columns=transformed_columns)
print("transformed DataFrame: ")
print(df_transformed.head())

# create new directory for plots:
plot_directory = "plots"
if not os.path.exists(plot_directory):
    os.makedirs(plot_directory)

# Box plots for numerical features
for col in numerical_cols:
    plt.figure(figsize=(10, 4))
    sns.boxplot(x=df[col])
    plt.title(f'Box plot of {col}')
    # plt.show()
    plt.savefig(f"{plot_directory}/boxplot_{col}.png")
    plt.close()

# the scatter plot between 'age' and 'trestbps'
plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['age'], y=df['trestbps'], hue=df['target'])
plt.title('Scatter plot between Age and Resting Blood Pressure')
plt.savefig(f"{plot_directory}/scatter_age_trestbps.png")
# plt.show()
plt.close()

After applied tranformations descriptions...
transformed DataFrame:
        age       sex   painloc  painexer  relrest        cp  trestbps       htn      chol  smoke      cigs     years       fbs  dm   famhist   restecg     ekgmo    ekgday     ekgyr       dig      prop      nitr       pro  diuretic     proto   thaldur  thaltime       met   thalach  thalrest  tpeakbps  tpeakbpd     dummy  trestbpd     exang     xhypo   oldpeak     slope  rldv5    rldv5e        ca  exerckm  restef  restwm  exeref  exerwm      thal  thalsev  thalpul  earlobe       cmo      cday       cyr  pncaden_None  restckm_None
0  0.561310  0.514214  0.238698  0.617624      NaN -2.428510  0.709406  1.048577  0.302816    NaN  1.689595  0.073642  2.234411 NaN  0.879337  1.739097 -1.140505 -1.426726 -1.864735 -0.190157 -0.325482 -0.602283 -0.456172 -0.356225 -0.720004  0.492504  0.077601 -0.113260  0.489447 -1.052198  0.713822  0.183823  0.673929  0.144068 -0.801264 -0.163896  1.323740  1.986915    NaN  1.942703 -0.663796      NaN     NaN     NaN     NaN     NaN  0.503854      NaN      NaN      NaN -1.187373  0.001269 -0.644561           1.0           1.0
1  0.819688  0.514214  0.238698  0.617624      NaN  0.804309  1.524297  1.048577  0.787251    NaN  1.142464  1.297511 -0.447545 NaN  0.879337  1.739097 -0.853513 -1.198331 -1.864735 -0.190157  0.823360 -0.602283 -0.456172 -0.356225 -0.720004  0.225438  0.077601 -0.113260 -1.129015 -0.780445 -0.452627  0.183823  1.457639  0.632042  1.248029 -0.163896  0.582932  0.376124    NaN  2.158400  2.190853      NaN     NaN     NaN     NaN     NaN -1.036917      NaN      NaN      NaN -1.187373 -1.240842 -0.644561           1.0           1.0
2  0.819688  0.514214  0.238698  0.617624      NaN  0.804309 -0.648745  1.048577  0.266255    NaN  0.048202  0.991543 -0.447545 NaN  0.879337  1.739097 -1.140505  0.400435 -1.864735 -0.190157  0.823360 -0.602283 -0.456172 -0.356225 -0.720004 -0.041628  0.077601 -0.210810 -0.319784  0.170692 -1.230259 -0.495258 -0.632255 -0.343905  1.248029 -0.163896  1.601542  0.376124    NaN  1.577676  1.239303      NaN     NaN     NaN     NaN     NaN  1.017444      NaN      NaN      NaN -1.187373  0.452945 -0.644561           1.0           1.0
3 -1.118143  0.514214  0.238698  0.617624      NaN -0.273297 -0.105485 -0.953673  0.458201    NaN -1.046059 -1.150227 -0.447545 NaN  0.879337 -0.750879 -1.140505 -0.284751 -1.864735 -0.190157  0.823360 -0.602283 -0.456172 -0.356225 -0.720004  1.160168  1.831902  0.016807  1.915234  0.578322  0.908230 -1.310156 -0.109782 -0.539095 -0.801264 -0.163896  2.434951  1.986915    NaN  1.859742 -0.663796      NaN     NaN     NaN     NaN     NaN -1.036917      NaN      NaN      NaN -1.187373 -1.353761 -0.644561           1.0           1.0
4 -0.859766 -1.944715  0.238698  0.617624      NaN -1.350903 -0.105485  1.048577  0.037748    NaN -1.046059 -1.150227 -0.447545 NaN  0.879337  1.739097 -1.140505 -0.969936 -1.864735 -0.190157 -0.325482 -0.602283 -0.456172 -0.356225 -0.720004 -0.442227       NaN -0.243327  1.337212 -0.304876 -0.452627 -0.902707 -0.109782  0.241663 -0.801264 -0.163896  0.490331 -1.234667    NaN -0.247457 -0.663796      NaN     NaN     NaN     NaN     NaN -1.036917      NaN      NaN      NaN -1.187373  0.227107 -0.644561           1.0           1.0

In [63]:
# add df_transformed to the database
try:
    df_transformed.to_sql('cleaned_heartdisease_data', con=engine, if_exists='replace', index=False)
    print("Data successfully stored in 'cleaned_heartdisease_data' table.")
except Exception as e:
    print(f"An error occurred: {e}")

Data successfully stored in 'cleaned_heartdisease_data' table.